spring:
 datasource:
  username: root
  password: Gkct@12345
  url: jdbc:mysql://localhost:3306/transportationdb1
  driver-class-name: com.mysql.jdbc.Driver 
 jpa :
  hibernate:
   ddl-auto: update
  show-sql: true